# Script para agregar 200 preguntas bíblicas
import json
import os

RUTA = os.path.join(os.path.dirname(__file__), 'preguntas', 'preguntas_biblicas.json')

NUEVAS_PREGUNTAS = [
    {"pregunta": "¿Qué animal habló a Balaam?", "opciones": ["Un león", "Un burro", "Un águila", "Una serpiente"], "respuesta_correcta": 1, "nivel": 1, "cita_biblica": "Números 22:28"},
    {"pregunta": "¿Quién fue vendido por sus hermanos a Egipto?", "opciones": ["Benjamín", "José", "Rubén", "Judá"], "respuesta_correcta": 1, "nivel": 1, "cita_biblica": "Génesis 37:28"},
    {"pregunta": "¿Cuántas plagas envió Dios a Egipto?", "opciones": ["7", "10", "12", "5"], "respuesta_correcta": 1, "nivel": 1, "cita_biblica": "Éxodo 7-12"},
    {"pregunta": "¿Quién sacó a Israel de Egipto?", "opciones": ["Josué", "Moisés", "Aarón", "Samuel"], "respuesta_correcta": 1, "nivel": 2, "cita_biblica": "Éxodo 3"},
    {"pregunta": "¿Qué mar cruzó Israel a pie seco?", "opciones": ["Mar Mediterráneo", "Mar Rojo", "Mar Muerto", "Mar de Galilea"], "respuesta_correcta": 1, "nivel": 2, "cita_biblica": "Éxodo 14"},
    {"pregunta": "¿Quién derrotó a Goliat?", "opciones": ["Saúl", "David", "Jonatán", "Samuel"], "respuesta_correcta": 1, "nivel": 2, "cita_biblica": "1 Samuel 17"},
    {"pregunta": "¿Qué rey construyó el primer templo en Jerusalén?", "opciones": ["David", "Salomón", "Ezequías", "Josías"], "respuesta_correcta": 1, "nivel": 2, "cita_biblica": "1 Reyes 6"},
    {"pregunta": "¿Quién fue el padre de Isaac?", "opciones": ["Noé", "Jacob", "Abraham", "Ismael"], "respuesta_correcta": 2, "nivel": 3, "cita_biblica": "Génesis 21"},
    {"pregunta": "¿Cuántos hijos tuvo Jacob?", "opciones": ["10", "12", "14", "7"], "respuesta_correcta": 1, "nivel": 3, "cita_biblica": "Génesis 35"},
    {"pregunta": "¿Quién fue la madre de Jesús?", "opciones": ["Ana", "María", "Elisabet", "Magdalena"], "respuesta_correcta": 1, "nivel": 3, "cita_biblica": "Lucas 1:30"},
    {"pregunta": "¿En qué día descansó Dios después de crear el mundo?", "opciones": ["Quinto", "Sexto", "Séptimo", "Octavo"], "respuesta_correcta": 2, "nivel": 3, "cita_biblica": "Génesis 2:2"},
    {"pregunta": "¿Qué señal pidió Gedeón a Dios?", "opciones": ["Arcoíris", "El rocío en el vellón", "Estrella", "Rayos"], "respuesta_correcta": 1, "nivel": 4, "cita_biblica": "Jueces 6:36-40"},
    {"pregunta": "¿Quién fue arrebatado al cielo en un carro de fuego?", "opciones": ["Enoc", "Elías", "Moisés", "Enoch"], "respuesta_correcta": 1, "nivel": 4, "cita_biblica": "2 Reyes 2:11"},
    {"pregunta": "¿Qué profeta fue tragado por un gran pez?", "opciones": ["Elías", "Jonás", "Daniel", "Ezequiel"], "respuesta_correcta": 1, "nivel": 4, "cita_biblica": "Jonás 1:17"},
    {"pregunta": "¿Cuántos libros tiene el Antiguo Testamento?", "opciones": ["36", "39", "42", "45"], "respuesta_correcta": 1, "nivel": 4, "cita_biblica": "Canon"},
    {"pregunta": "¿Quién interpretó el sueño del faraón?", "opciones": ["Daniel", "José", "Moisés", "Samuel"], "respuesta_correcta": 1, "nivel": 5, "cita_biblica": "Génesis 41"},
    {"pregunta": "¿Qué mujer salvó a los espías en Jericó?", "opciones": ["Rut", "Rahab", "Raquel", "Rebeca"], "respuesta_correcta": 1, "nivel": 5, "cita_biblica": "Josué 2"},
    {"pregunta": "¿Quién fue el sucesor de Moisés?", "opciones": ["Caleb", "Josué", "Eleazar", "Aaron"], "respuesta_correcta": 1, "nivel": 5, "cita_biblica": "Josué 1"},
    {"pregunta": "¿ Qué apóstol dudó de la resurrección de Jesús?", "opciones": ["Pedro", "Tomás", "Andrés", "Felipe"], "respuesta_correcta": 1, "nivel": 5, "cita_biblica": "Juan 20:24-29"},
    {"pregunta": "¿Cuántos panes y peces multiplicó Jesús para alimentar a la multitud?", "opciones": ["3 panes y 2 peces", "5 panes y 2 peces", "7 panes y 3 peces", "2 panes y 5 peces"], "respuesta_correcta": 1, "nivel": 6, "cita_biblica": "Juan 6:9"},
    {"pregunta": "¿Quién bautizó a Jesús?", "opciones": ["Pedro", "Juan el Bautista", "Andrés", "Felipe"], "respuesta_correcta": 1, "nivel": 6, "cita_biblica": "Mateo 3:13"},
    {"pregunta": "¿En qué día resucitó Jesús?", "opciones": ["Viernes", "Sábado", "Domingo", "Lunes"], "respuesta_correcta": 2, "nivel": 6, "cita_biblica": "Mateo 28:1"},
    {"pregunta": "¿Quién fue el rey que pidió la cabeza de Juan el Bautista?", "opciones": ["Pilato", "Herodes", "César", "Anás"], "respuesta_correcta": 1, "nivel": 6, "cita_biblica": "Mateo 14:1-12"},
    {"pregunta": "¿Qué apóstol era cobrador de impuestos?", "opciones": ["Mateo", "Simón", "Tadeo", "Bartolomé"], "respuesta_correcta": 0, "nivel": 7, "cita_biblica": "Mateo 9:9"},
    {"pregunta": "¿Quién resucitó a Lázaro?", "opciones": ["Pedro", "Pablo", "Jesús", "Elías"], "respuesta_correcta": 2, "nivel": 7, "cita_biblica": "Juan 11"},
    {"pregunta": "¿Cuál fue la última cena de Jesús con sus discípulos?", "opciones": ["Pascua", "Pentecostés", "Fiesta de los Tabernáculos", "Hanukkah"], "respuesta_correcta": 0, "nivel": 7, "cita_biblica": "Mateo 26:17"},
    {"pregunta": "¿Qué apóstol escribió el libro de Apocalipsis?", "opciones": ["Pedro", "Pablo", "Juan", "Santiago"], "respuesta_correcta": 2, "nivel": 7, "cita_biblica": "Apocalipsis 1:1"},
    {"pregunta": "¿Quién fue el sumo sacerdote que condenó a Jesús?", "opciones": ["Herodes", "Caifás", "Pilato", "Anás"], "respuesta_correcta": 1, "nivel": 8, "cita_biblica": "Mateo 26:57"},
    {"pregunta": "¿En qué monte fue Jesús transfigurado?", "opciones": ["Sinaí", "Sion", "Tabor", "Olivos"], "respuesta_correcta": 2, "nivel": 8, "cita_biblica": "Mateo 17:1"},
    {"pregunta": "¿Quién fue el gobernador romano que entregó a Jesús para ser crucificado?", "opciones": ["Herodes", "Poncio Pilato", "Caifás", "Félix"], "respuesta_correcta": 1, "nivel": 8, "cita_biblica": "Mateo 27:26"},
    {"pregunta": "¿Cuántas tentaciones tuvo Jesús en el desierto?", "opciones": ["2", "3", "4", "7"], "respuesta_correcta": 1, "nivel": 8, "cita_biblica": "Mateo 4:1-11"},
    {"pregunta": "¿Qué apóstol era hermano de Pedro?", "opciones": ["Juan", "Andrés", "Felipe", "Tomás"], "respuesta_correcta": 1, "nivel": 9, "cita_biblica": "Mateo 4:18"},
    {"pregunta": "¿Quién fue la esposa de Abraham?", "opciones": ["Rebeca", "Raquel", "Sara", "Lea"], "respuesta_correcta": 2, "nivel": 9, "cita_biblica": "Génesis 17:15"},
    {"pregunta": "¿Qué significa el nombre 'Jesús'?", "opciones": ["Rey de reyes", "Dios con nosotros", "Salvador", "Mesías"], "respuesta_correcta": 2, "nivel": 9, "cita_biblica": "Mateo 1:21"},
    {"pregunta": "¿Quién fue el padre de Juan el Bautista según el ángel?", "opciones": ["Zacarías", "José", "Eli", "Abraham"], "respuesta_correcta": 0, "nivel": 9, "cita_biblica": "Lucas 1:13"},
    {"pregunta": "¿En qué ciudad creció Jesús?", "opciones": ["Belén", "Jerusalén", "Nazaret", "Galilea"], "respuesta_correcta": 2, "nivel": 10, "cita_biblica": "Lucas 2:39"},
    {"pregunta": "¿Cuántos hijos de Israel fueron a Egipto con Jacob?", "opciones": ["11", "12", "70", "66"], "respuesta_correcta": 2, "nivel": 10, "cita_biblica": "Génesis 46:27"},
    {"pregunta": "¿Qué rey propuso cortar un niño por la mitad?", "opciones": ["David", "Salomón", "Saúl", "Roboam"], "respuesta_correcta": 1, "nivel": 10, "cita_biblica": "1 Reyes 3:16-28"},
    {"pregunta": "¿Quién fue la madre de Salomón?", "opciones": ["Mical", "Abigail", "Betsabé", "Ana"], "respuesta_correcta": 2, "nivel": 10, "cita_biblica": "2 Samuel 12:24"},
    {"pregunta": "¿Qué animal engañó a Eva en el Edén?", "opciones": ["Un ángel", "Una serpiente", "Un león", "Un águila"], "respuesta_correcta": 1, "nivel": 11, "cita_biblica": "Génesis 3:1"},
    {"pregunta": "¿Cuántas veces negó Pedro a Jesús?", "opciones": ["1", "2", "3", "4"], "respuesta_correcta": 2, "nivel": 11, "cita_biblica": "Mateo 26:69-75"},
    {"pregunta": "¿Quién fue arrojado al foso de los leones?", "opciones": ["José", "Daniel", "Sadrac", "Jeremías"], "respuesta_correcta": 1, "nivel": 11, "cita_biblica": "Daniel 6"},
    {"pregunta": "¿En qué libro está la historia de Rut?", "opciones": ["Jueces", "Rut", "1 Samuel", "Génesis"], "respuesta_correcta": 1, "nivel": 11, "cita_biblica": "Libro de Rut"},
    {"pregunta": "¿Quién fue el bisabuelo del rey David?", "opciones": ["Isaí", "Booz", "Obed", "Rut"], "respuesta_correcta": 1, "nivel": 12, "cita_biblica": "Rut 4:21"},
    {"pregunta": "¿Qué profeta fue llevado al cielo sin morir?", "opciones": ["Enoc", "Elías", "Moisés", "Enoch"], "respuesta_correcta": 1, "nivel": 12, "cita_biblica": "2 Reyes 2:11"},
    {"pregunta": "¿Cuántos leprosos curó Jesús y solo uno volvió a dar gracias?", "opciones": ["5", "7", "10", "12"], "respuesta_correcta": 2, "nivel": 12, "cita_biblica": "Lucas 17:12-19"},
    {"pregunta": "¿Quién fue el hermano de Moisés?", "opciones": ["Josué", "Aarón", "Caleb", "Eleazar"], "respuesta_correcta": 1, "nivel": 12, "cita_biblica": "Éxodo 4:14"},
    {"pregunta": "¿Qué maná recibió Israel en el desierto?", "opciones": ["Carne", "Pan del cielo", "Agua", "Miel"], "respuesta_correcta": 1, "nivel": 13, "cita_biblica": "Éxodo 16"},
    {"pregunta": "¿Quién fue el rey más joven de Judá?", "opciones": ["Josías", "Joás", "Ezequías", "Manasés"], "respuesta_correcta": 1, "nivel": 13, "cita_biblica": "2 Reyes 11:21"},
    {"pregunta": "¿En qué pueblo vivió Lázaro con sus hermanas?", "opciones": ["Betania", "Belén", "Nazaret", "Caná"], "respuesta_correcta": 0, "nivel": 13, "cita_biblica": "Juan 11:1"},
    {"pregunta": "¿Qué mujer fue madre de Samuel?", "opciones": ["Raquel", "Ana", "Ester", "Rut"], "respuesta_correcta": 1, "nivel": 13, "cita_biblica": "1 Samuel 1"},
    {"pregunta": "¿Cuántas tribus tenía Israel?", "opciones": ["10", "12", "13", "14"], "respuesta_correcta": 1, "nivel": 14, "cita_biblica": "Génesis 49"},
    {"pregunta": "¿Quién fue el profeta que confrontó a Acab?", "opciones": [" Eliseo", "Elías", "Samuel", "Natán"], "respuesta_correcta": 1, "nivel": 14, "cita_biblica": "1 Reyes 18"},
    {"pregunta": "¿Qué hizo Jesús con los cambistas en el templo?", "opciones": ["Los bendijo", "Los expulsó", "Los enseñó", "Los sanó"], "respuesta_correcta": 1, "nivel": 14, "cita_biblica": "Juan 2:15"},
    {"pregunta": "¿Quién fue el discípulo amado de Jesús?", "opciones": ["Pedro", "Juan", "Santiago", "Andrés"], "respuesta_correcta": 1, "nivel": 14, "cita_biblica": "Juan 13:23"},
    {"pregunta": "¿En qué día de la semana murió Jesús?", "opciones": ["Jueves", "Viernes", "Sábado", "Domingo"], "respuesta_correcta": 1, "nivel": 15, "cita_biblica": "Juan 19:31"},
    {"pregunta": "¿Cuántos animales de cada especie entraron en el arca?", "opciones": ["1 pareja", "2 parejas", "7 parejas de limpios", "Varios según especies"], "respuesta_correcta": 2, "nivel": 15, "cita_biblica": "Génesis 7:2"},
    {"pregunta": "¿Quién fue el rey que bailó delante del arca?", "opciones": ["Salomón", "David", "Saúl", "Josafat"], "respuesta_correcta": 1, "nivel": 15, "cita_biblica": "2 Samuel 6:14"},
    {"pregunta": "¿Qué apóstol era gemelo?", "opciones": ["Tomás", "Judas", "Simón", "Mateo"], "respuesta_correcta": 0, "nivel": 15, "cita_biblica": "Juan 11:16"},
    {"pregunta": "¿Dónde nació el apóstol Pablo?", "opciones": ["Jerusalén", "Tarso", "Antioquía", "Romanos"], "respuesta_correcta": 1, "nivel": 1, "cita_biblica": "Hechos 21:39"},
    {"pregunta": "¿Qué libro del NT tiene 28 capítulos?", "opciones": ["Mateo", "Marcos", "Lucas", "Juan"], "respuesta_correcta": 0, "nivel": 1, "cita_biblica": "Mateo"},
    {"pregunta": "¿Quién fue el rey que pidió sabiduría a Dios?", "opciones": ["David", "Salomón", "Ezequías", "Josías"], "respuesta_correcta": 1, "nivel": 2, "cita_biblica": "1 Reyes 3:9"},
    {"pregunta": "¿Cuántos años tenía Isaac cuando se casó con Rebeca?", "opciones": ["25", "35", "40", "50"], "respuesta_correcta": 2, "nivel": 2, "cita_biblica": "Génesis 25:20"},
    {"pregunta": "¿Qué significa 'Cristo'?", "opciones": ["Rey", "Ungido", "Salvador", "Señor"], "respuesta_correcta": 1, "nivel": 2, "cita_biblica": "Título mesiánico"},
    {"pregunta": "¿Quién fue enviado a Nínive a predicar?", "opciones": ["Elías", "Jonás", "Daniel", "Jeremías"], "respuesta_correcta": 1, "nivel": 3, "cita_biblica": "Jonás 1:2"},
    {"pregunta": "¿Cuántos años duró el diluvio sobre la tierra?", "opciones": ["40 días", "150 días", "1 año", "2 años"], "respuesta_correcta": 2, "nivel": 3, "cita_biblica": "Génesis 7-8"},
    {"pregunta": "¿Qué evangelista era médico?", "opciones": ["Mateo", "Marcos", "Lucas", "Juan"], "respuesta_correcta": 2, "nivel": 3, "cita_biblica": "Colosenses 4:14"},
    {"pregunta": "¿Quién fue entregado a Poncio Pilato?", "opciones": ["Barrabás", "Jesús", "Pedro", "Pablo"], "respuesta_correcta": 1, "nivel": 4, "cita_biblica": "Mateo 27:2"},
    {"pregunta": "¿En qué lugar Jesús alimentó a los 5000?", "opciones": ["Desierto", "Colina cerca del mar", "Jerusalén", "Nazaret"], "respuesta_correcta": 1, "nivel": 4, "cita_biblica": "Juan 6:1-15"},
    {"pregunta": "¿Qué profeta fue enviado a la viuda de Sarepta?", "opciones": ["Isaías", "Elías", "Ezequiel", "Jeremías"], "respuesta_correcta": 1, "nivel": 4, "cita_biblica": "1 Reyes 17:9"},
    {"pregunta": "¿Quién fue padre de Ismael?", "opciones": ["Jacob", "Isaac", "Abraham", "Lot"], "respuesta_correcta": 2, "nivel": 5, "cita_biblica": "Génesis 16:15"},
    {"pregunta": "¿Cuántas cuerdas tenía el arpa de David?", "opciones": ["No se especifica", "10", "12", "7"], "respuesta_correcta": 0, "nivel": 5, "cita_biblica": "1 Samuel 16:23"},
    {"pregunta": "¿Qué árbol vio Nabucodonosor en su sueño?", "opciones": ["Olivo", "Higuera", "Gran árbol", "Cedro"], "respuesta_correcta": 2, "nivel": 5, "cita_biblica": "Daniel 4"},
    {"pregunta": "¿Quién fue el primer mártir cristiano apedreado?", "opciones": ["Pablo", "Pedro", "Esteban", "Santiago"], "respuesta_correcta": 2, "nivel": 6, "cita_biblica": "Hechos 7:59"},
    {"pregunta": "¿En qué idioma estaba escrito el letrero de la cruz?", "opciones": ["Solo hebreo", "Hebreo, griego y latín", "Solo griego", "Latín y hebreo"], "respuesta_correcta": 1, "nivel": 6, "cita_biblica": "Juan 19:20"},
    {"pregunta": "¿Qué reina visitó a Salomón?", "opciones": ["De Saba", "De Etiopía", "De Egipto", "De Babilonia"], "respuesta_correcta": 0, "nivel": 6, "cita_biblica": "1 Reyes 10"},
    {"pregunta": "¿Cuántas veces perdonar según Jesús?", "opciones": ["7", "70 veces 7", "100", "Ilimitado"], "respuesta_correcta": 1, "nivel": 7, "cita_biblica": "Mateo 18:22"},
    {"pregunta": "¿Quién fue el padre de Moisés?", "opciones": ["Amram", "Aarón", "Ceoré", "Leví"], "respuesta_correcta": 0, "nivel": 7, "cita_biblica": "Éxodo 6:20"},
    {"pregunta": "¿Qué manó Caín a Abel?", "opciones": ["Con una espada", "Con una piedra", "No se especifica", "Con un palo"], "respuesta_correcta": 2, "nivel": 7, "cita_biblica": "Génesis 4:8"},
    {"pregunta": "¿Cuántos años tenía José cuando fue vendido?", "opciones": ["15", "17", "20", "25"], "respuesta_correcta": 1, "nivel": 8, "cita_biblica": "Génesis 37:2"},
    {"pregunta": "¿Qué mujer fue madre de Salomón?", "opciones": ["Mical", "Betsabé", "Abigail", "Ahinoam"], "respuesta_correcta": 1, "nivel": 8, "cita_biblica": "2 Samuel 12:24"},
    {"pregunta": "¿Quién fue el rey que tuvo 700 esposas?", "opciones": ["David", "Salomón", "Roboam", "Acab"], "respuesta_correcta": 1, "nivel": 8, "cita_biblica": "1 Reyes 11:3"},
    {"pregunta": "¿En qué río Naamán se lavó siete veces?", "opciones": ["Jordán", "Nilo", "Éufrates", "Tigris"], "respuesta_correcta": 0, "nivel": 9, "cita_biblica": "2 Reyes 5:14"},
    {"pregunta": "¿Qué apóstol era conocido como el Zelote?", "opciones": ["Simón", "Judas", "Tadeo", "Bartolomé"], "respuesta_correcta": 0, "nivel": 9, "cita_biblica": "Lucas 6:15"},
    {"pregunta": "¿Quién fue el faraón en tiempos de José?", "opciones": ["Ramsés", "No se nombra", "Amenhotep", "Tutankamón"], "respuesta_correcta": 1, "nivel": 9, "cita_biblica": "Génesis 41"},
    {"pregunta": "¿Cuántos años vivió Noé?", "opciones": ["600", "800", "950", "969"], "respuesta_correcta": 2, "nivel": 10, "cita_biblica": "Génesis 9:29"},
    {"pregunta": "¿Qué ave llevó una rama de olivo a Noé?", "opciones": ["Cuervo", "Paloma", "Águila", "Golondrina"], "respuesta_correcta": 1, "nivel": 10, "cita_biblica": "Génesis 8:11"},
    {"pregunta": "¿Quién fue el padre de Juan el Bautista?", "opciones": ["Zacarías", "José", "Eli", "Joacim"], "respuesta_correcta": 0, "nivel": 10, "cita_biblica": "Lucas 1:5"},
    {"pregunta": "¿En qué libro está el Sermón del Monte?", "opciones": ["Marcos", "Lucas", "Mateo", "Juan"], "respuesta_correcta": 2, "nivel": 11, "cita_biblica": "Mateo 5-7"},
    {"pregunta": "¿Qué fruto del Espíritu se menciona primero en Gálatas?", "opciones": ["Gozo", "Amor", "Paz", "Paciencia"], "respuesta_correcta": 1, "nivel": 11, "cita_biblica": "Gálatas 5:22"},
    {"pregunta": "¿Quién fue el profeta que vio la rueda dentro de rueda?", "opciones": ["Daniel", "Ezequiel", "Isaías", "Jeremías"], "respuesta_correcta": 1, "nivel": 11, "cita_biblica": "Ezequiel 1"},
    {"pregunta": "¿Cuántos capítulos tiene el libro de Salmos?", "opciones": ["100", "119", "150", "73"], "respuesta_correcta": 2, "nivel": 12, "cita_biblica": "Salmos"},
    {"pregunta": "¿Quién fue el rey que escribió muchos Salmos?", "opciones": ["Salomón", "David", "Ezequías", "Josafat"], "respuesta_correcta": 1, "nivel": 12, "cita_biblica": "Salmos"},
    {"pregunta": "¿En qué ciudad Pablo fue ciudadano romano?", "opciones": ["Tarso", "Jerusalén", "Antioquía", "Corinto"], "respuesta_correcta": 0, "nivel": 12, "cita_biblica": "Hechos 21:39"},
    {"pregunta": "¿Qué personaje duró 40 días en el arca antes del diluvio?", "opciones": ["Noé", "Los animales", "7 días según algunos", "No aplica"], "respuesta_correcta": 2, "nivel": 13, "cita_biblica": "Génesis 7:4"},
    {"pregunta": "¿Quién fue la madre de Moisés?", "opciones": ["Jocabed", "Séfora", "Miriam", "Zipporah"], "respuesta_correcta": 0, "nivel": 13, "cita_biblica": "Éxodo 2:1"},
    {"pregunta": "¿Cuántas veces tocó Josué las trompetas en Jericó?", "opciones": ["1 vez", "7 veces en 7 días", "40 veces", "13 veces"], "respuesta_correcta": 1, "nivel": 13, "cita_biblica": "Josué 6"},
    {"pregunta": "¿Qué montaña vio Moisés antes de morir?", "opciones": ["Sinaí", "Nebo", "Pisga", "Seir"], "respuesta_correcta": 1, "nivel": 14, "cita_biblica": "Deuteronomio 34:1"},
    {"pregunta": "¿Quién fue el juez que tenía 30 hijos?", "opciones": ["Gedeón", "Jefté", "Jair", "Ibzan"], "respuesta_correcta": 2, "nivel": 14, "cita_biblica": "Jueces 10:4"},
    {"pregunta": "¿En qué verso está 'Porque de tal manera amó Dios al mundo'?", "opciones": ["Juan 3:15", "Juan 3:16", "Juan 3:17", "1 Juan 4:8"], "respuesta_correcta": 1, "nivel": 14, "cita_biblica": "Juan 3:16"},
    {"pregunta": "¿Cuántos libros hay en la ley de Moisés (Pentateuco)?", "opciones": ["3", "5", "7", "12"], "respuesta_correcta": 1, "nivel": 15, "cita_biblica": "Pentateuco"},
    {"pregunta": "¿Quién fue el primer rey de Judá tras la división?", "opciones": ["Roboam", "Jeroboam", "Abías", "Asa"], "respuesta_correcta": 0, "nivel": 15, "cita_biblica": "1 Reyes 12"},
    {"pregunta": "¿Qué escribió Jesús en la tierra cuando trajeron a la adúltera?", "opciones": ["No se dice", "Los pecados", "Nada", "La ley"], "respuesta_correcta": 0, "nivel": 15, "cita_biblica": "Juan 8:6"},
    {"pregunta": "¿Quién fue el profeta que ayunó 40 días?", "opciones": ["Elías", "Moisés", "Daniel", "Todos ellos"], "respuesta_correcta": 3, "nivel": 15, "cita_biblica": "Éxodo 34:28, 1 Reyes 19:8, Daniel 10"},
    {"pregunta": "¿Cuántas veces cayó Jesús camino a la cruz según la tradición?", "opciones": ["1", "2", "3", "No se registra"], "respuesta_correcta": 3, "nivel": 1, "cita_biblica": "Tradición"},
    {"pregunta": "¿Qué animal mencionó Jesús como ejemplo de astucia?", "opciones": ["Zorro", "Serpiente", "Lobo", "Águila"], "respuesta_correcta": 0, "nivel": 2, "cita_biblica": "Lucas 13:32"},
    {"pregunta": "¿Quién fue el rey que pidió la sabiduría de Salomón?", "opciones": ["Reina de Saba", "Faraón", "Hiram", "Ninguno"], "respuesta_correcta": 0, "nivel": 2, "cita_biblica": "1 Reyes 10"},
    {"pregunta": "¿En qué festividad fue crucificado Jesús?", "opciones": ["Hanukkah", "Pascua", "Pentecostés", "Tabernáculos"], "respuesta_correcta": 1, "nivel": 3, "cita_biblica": "Juan 19:14"},
    {"pregunta": "¿Cuántos años tenía Josías cuando comenzó a reinar?", "opciones": ["6", "8", "12", "16"], "respuesta_correcta": 1, "nivel": 3, "cita_biblica": "2 Reyes 22:1"},
    {"pregunta": "¿Qué apóstol era hermano de Santiago?", "opciones": ["Pedro", "Juan", "Andrés", "Felipe"], "respuesta_correcta": 1, "nivel": 4, "cita_biblica": "Hechos 12:2"},
    {"pregunta": "¿Quién fue el sumo sacerdote cuando nació Jesús?", "opciones": ["Caifás", "Anás", "No se especifica", "Zacarías"], "respuesta_correcta": 2, "nivel": 4, "cita_biblica": "Lucas 2"},
    {"pregunta": "¿Qué lago recorrió Jesús predicando?", "opciones": ["Mar Muerto", "Mar de Galilea", "Mar Rojo", "Lago de Genesaret"], "respuesta_correcta": 1, "nivel": 5, "cita_biblica": "Mateo 4:18"},
    {"pregunta": "¿Cuántas veces aparece la palabra 'amén' en la Biblia?", "opciones": ["Aproximadamente 50", "Más de 100", "Más de 50", "Variable"], "respuesta_correcta": 2, "nivel": 5, "cita_biblica": "Biblia"},
    {"pregunta": "¿Quién fue el padre de Esaú y Jacob?", "opciones": ["Abraham", "Isaac", "Ismael", "Nacor"], "respuesta_correcta": 1, "nivel": 6, "cita_biblica": "Génesis 25:19"},
    {"pregunta": "¿Qué rey encontró el libro de la ley en el templo?", "opciones": ["Ezequías", "Josías", "Joás", "Asa"], "respuesta_correcta": 1, "nivel": 6, "cita_biblica": "2 Reyes 22:8"},
    {"pregunta": "¿En qué desierto Israel vagó 40 años?", "opciones": ["Sinaí", "Paran", "Zin", "Varios"], "respuesta_correcta": 0, "nivel": 7, "cita_biblica": "Números 14:33"},
    {"pregunta": "¿Quién fue la madre de Isaac?", "opciones": ["Agar", "Sara", "Rebeca", "Ketura"], "respuesta_correcta": 1, "nivel": 7, "cita_biblica": "Génesis 21:2"},
    {"pregunta": "¿Qué don del Espíritu recibieron los apóstoles en Pentecostés?", "opciones": ["Sabiduría", "Hablar en lenguas", "Sanidad", "Profecía"], "respuesta_correcta": 1, "nivel": 8, "cita_biblica": "Hechos 2:4"},
    {"pregunta": "¿Cuántos hombres vio Ezequiel en la visión del valle?", "opciones": ["Miles", "Innumerables", "Muchos", "No se da número"], "respuesta_correcta": 2, "nivel": 8, "cita_biblica": "Ezequiel 37"},
    {"pregunta": "¿Quién fue el rey que destruyó los altares de Baal?", "opciones": ["Josías", "Ezequías", "Jehú", "Varios"], "respuesta_correcta": 3, "nivel": 9, "cita_biblica": "2 Reyes 10, 18, 23"},
    {"pregunta": "¿En qué libro está la historia de Ester?", "opciones": ["Nehemías", "Ester", "Esdras", "Crónicas"], "respuesta_correcta": 1, "nivel": 9, "cita_biblica": "Ester"},
    {"pregunta": "¿Qué rey persa permitió reconstruir el templo?", "opciones": ["Nabucodonosor", "Ciro", "Darío", "Artajerjes"], "respuesta_correcta": 1, "nivel": 10, "cita_biblica": "Esdras 1"},
    {"pregunta": "¿Cuántos años tenía Enoc cuando fue llevado?", "opciones": ["300", "365", "400", "500"], "respuesta_correcta": 1, "nivel": 10, "cita_biblica": "Génesis 5:23"},
    {"pregunta": "¿Quién fue el profeta que profetizó en el exilio babilónico?", "opciones": ["Jeremías", "Ezequiel", "Daniel", "Isaías"], "respuesta_correcta": 1, "nivel": 11, "cita_biblica": "Ezequiel 1:1"},
    {"pregunta": "¿Qué ofrenda dio la viuda que Jesús alabó?", "opciones": ["2 monedas", "Una moneda", "Todo lo que tenía", "2 blancas"], "respuesta_correcta": 0, "nivel": 11, "cita_biblica": "Marcos 12:42"},
    {"pregunta": "¿En qué ciudad Pablo predicó en el Areópago?", "opciones": ["Corinto", "Éfeso", "Atenas", "Roma"], "respuesta_correcta": 2, "nivel": 12, "cita_biblica": "Hechos 17:22"},
    {"pregunta": "¿Quién fue el sobrino de Abraham?", "opciones": ["Isaac", "Lot", "Nacor", "Ismael"], "respuesta_correcta": 1, "nivel": 12, "cita_biblica": "Génesis 12:5"},
    {"pregunta": "¿Cuántos hijos tuvo Job después de sus pruebas?", "opciones": ["7", "10", "12", "14"], "respuesta_correcta": 3, "nivel": 13, "cita_biblica": "Job 42:13"},
    {"pregunta": "¿Qué rey tuvo lepra?", "opciones": ["David", "Salomón", "Uzías", "Ezequías"], "respuesta_correcta": 2, "nivel": 13, "cita_biblica": "2 Crónicas 26:19"},
    {"pregunta": "¿Quién fue el escriba que leyó la ley a Esdras?", "opciones": ["Nehemías", "Los levitas", "Esdras mismo", "El pueblo"], "respuesta_correcta": 1, "nivel": 14, "cita_biblica": "Nehemías 8"},
    {"pregunta": "¿En qué libro está 'El Señor es mi pastor'?", "opciones": ["Proverbios", "Salmos 23", "Isaías", "Ezequiel"], "respuesta_correcta": 1, "nivel": 14, "cita_biblica": "Salmos 23:1"},
    {"pregunta": "¿Cuántas veces oró Jesús en Getsemaní?", "opciones": ["1", "2", "3", "Varias"], "respuesta_correcta": 2, "nivel": 15, "cita_biblica": "Mateo 26:36-44"},
    {"pregunta": "¿Quién fue el primer discípulo llamado por Jesús?", "opciones": ["Pedro", "Andrés", "Juan", "Felipe"], "respuesta_correcta": 1, "nivel": 15, "cita_biblica": "Juan 1:40"},
    {"pregunta": "¿Qué significa 'Hosanna'?", "opciones": ["Gloria", "Sálvanos ahora", "Aleluya", "Amén"], "respuesta_correcta": 1, "nivel": 1, "cita_biblica": "Mateo 21:9"},
    {"pregunta": "¿Quién fue el rey que escribió Eclesiastés?", "opciones": ["David", "Salomón", "Ezequías", "Josías"], "respuesta_correcta": 1, "nivel": 2, "cita_biblica": "Eclesiastés 1:1"},
    {"pregunta": "¿En qué ciudad vivía Lázaro cuando Jesús lo resucitó?", "opciones": ["Betania", "Belén", "Nazaret", "Caná"], "respuesta_correcta": 0, "nivel": 3, "cita_biblica": "Juan 11"},
    {"pregunta": "¿Cuántos eran los hombres que llevaron al paralítico al techo?", "opciones": ["2", "3", "4", "5"], "respuesta_correcta": 2, "nivel": 4, "cita_biblica": "Marcos 2:3"},
    {"pregunta": "¿Qué persona del AT fue transfigurada con Jesús?", "opciones": ["Enoc", "Elías y Moisés", "David", "Abraham"], "respuesta_correcta": 1, "nivel": 5, "cita_biblica": "Mateo 17:3"},
    {"pregunta": "¿Quién fue el rey que consultó a la bruja de Endor?", "opciones": ["David", "Salomón", "Saúl", "Roboam"], "respuesta_correcta": 2, "nivel": 6, "cita_biblica": "1 Samuel 28"},
    {"pregunta": "¿En qué río fue bautizado el eunuco etíope?", "opciones": ["Jordán", "Un camino con agua", "No se dice", "Nilo"], "respuesta_correcta": 1, "nivel": 7, "cita_biblica": "Hechos 8:36"},
    {"pregunta": "¿Cuántas veces gritó Jesús en la cruz 'Dios mío'?", "opciones": ["1", "2", "3", "No se registra"], "respuesta_correcta": 0, "nivel": 8, "cita_biblica": "Mateo 27:46"},
    {"pregunta": "¿Qué alimento pidió el hijo pródigo cuando volvió?", "opciones": ["Pan", "Lo que comían los cerdos", "No pidió", "Comida del padre"], "respuesta_correcta": 3, "nivel": 9, "cita_biblica": "Lucas 15"},
    {"pregunta": "¿Quién fue el padre de Jacob?", "opciones": ["Abraham", "Isaac", "Esau", "Nacor"], "respuesta_correcta": 1, "nivel": 10, "cita_biblica": "Génesis 25:26"},
    {"pregunta": "¿Qué libro sigue a Deuteronomio?", "opciones": ["Josué", "Jueces", "Rut", "1 Samuel"], "respuesta_correcta": 0, "nivel": 11, "cita_biblica": "Canon"},
    {"pregunta": "¿Cuántos reyes magos visitaron a Jesús según la tradición?", "opciones": ["2", "3", "4", "No se especifica"], "respuesta_correcta": 3, "nivel": 12, "cita_biblica": "Mateo 2:1"},
    {"pregunta": "¿Quién fue el profeta que dijo 'He aquí el Cordero de Dios'?", "opciones": ["Pedro", "Juan el Bautista", "Andrés", "Felipe"], "respuesta_correcta": 1, "nivel": 13, "cita_biblica": "Juan 1:29"},
    {"pregunta": "¿En qué ciudad nació el apóstol Pablo?", "opciones": ["Tarso", "Jerusalén", "Antioquía", "Damasco"], "respuesta_correcta": 0, "nivel": 14, "cita_biblica": "Hechos 21:39"},
    {"pregunta": "¿Qué apóstol era publicano antes de seguir a Jesús?", "opciones": ["Mateo", "Simón", "Judas", "Tadeo"], "respuesta_correcta": 0, "nivel": 15, "cita_biblica": "Mateo 9:9"},
]

with open(RUTA, 'r', encoding='utf-8') as f:
    data = json.load(f)

data['preguntas'].extend(NUEVAS_PREGUNTAS)

with open(RUTA, 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"Se agregaron {len(NUEVAS_PREGUNTAS)} preguntas. Total: {len(data['preguntas'])}")
